// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinecraftSpec) DeepCopyInto(out *MinecraftSpec) {
	*out = *in
	if in.UserOps != nil {
		in, out := &in.UserOps, &out.UserOps
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinecraftSpec.
func (in *MinecraftSpec) DeepCopy() *MinecraftSpec {
	if in == nil {
		return nil
	}
	out := new(MinecraftSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Spigot) DeepCopyInto(out *Spigot) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Spigot.
func (in *Spigot) DeepCopy() *Spigot {
	if in == nil {
		return nil
	}
	out := new(Spigot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Spigot) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpigotList) DeepCopyInto(out *SpigotList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Spigot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpigotList.
func (in *SpigotList) DeepCopy() *SpigotList {
	if in == nil {
		return nil
	}
	out := new(SpigotList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SpigotList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpigotSpec) DeepCopyInto(out *SpigotSpec) {
	*out = *in
	in.Minecraft.DeepCopyInto(&out.Minecraft)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpigotSpec.
func (in *SpigotSpec) DeepCopy() *SpigotSpec {
	if in == nil {
		return nil
	}
	out := new(SpigotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpigotStatus) DeepCopyInto(out *SpigotStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpigotStatus.
func (in *SpigotStatus) DeepCopy() *SpigotStatus {
	if in == nil {
		return nil
	}
	out := new(SpigotStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Vanilla) DeepCopyInto(out *Vanilla) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Vanilla.
func (in *Vanilla) DeepCopy() *Vanilla {
	if in == nil {
		return nil
	}
	out := new(Vanilla)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Vanilla) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VanillaList) DeepCopyInto(out *VanillaList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Vanilla, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VanillaList.
func (in *VanillaList) DeepCopy() *VanillaList {
	if in == nil {
		return nil
	}
	out := new(VanillaList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VanillaList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VanillaSpec) DeepCopyInto(out *VanillaSpec) {
	*out = *in
	in.Minecraft.DeepCopyInto(&out.Minecraft)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VanillaSpec.
func (in *VanillaSpec) DeepCopy() *VanillaSpec {
	if in == nil {
		return nil
	}
	out := new(VanillaSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VanillaStatus) DeepCopyInto(out *VanillaStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VanillaStatus.
func (in *VanillaStatus) DeepCopy() *VanillaStatus {
	if in == nil {
		return nil
	}
	out := new(VanillaStatus)
	in.DeepCopyInto(out)
	return out
}
