apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: vanillas.minecraft.noltarium.de
spec:
  group: minecraft.noltarium.de
  names:
    kind: Vanilla
    listKind: VanillaList
    plural: vanillas
    singular: vanilla
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Vanilla is the Schema for the vanillas API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: VanillaSpec defines the desired state of Vanilla
          properties:
            minecraft:
              properties:
                acceptEula:
                  type: boolean
                ops:
                  items:
                    type: string
                  maxItems: 500
                  minItems: 1
                  type: array
              type: object
          type: object
        status:
          description: VanillaStatus defines the observed state of Vanilla
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
